In [2]:
'''	
@Author: Aishwarya
@Date: 2021-12-6
@Title: create a 2d array with 0 on the border and 1 inside
'''
########################################################################################################
import numpy as np

import numpy as np
arr = np.zeros((5,5))
print("Array:")
print(arr)
print("------------------------------------------------")
print("0 on the border and 1 inside array")
arr[1:-1,1:-1] = 1
print(arr)

Array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------------------------------------
0 on the border and 1 inside array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
