In [2]:
'''	
@Author: Aishwarya
@Date: 2021-12-7
@Title : change the data type of an array.
'''
########################################################################################################
import numpy as np

array = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print("Array : ",array)
print("Data type of the array array is:",array.dtype)
# Change the data type of array
arr= array.astype(float)
print("New Array: ",arr.dtype)
print(arr)


Array :  [[ 2  4  6]
 [ 6  8 10]]
Data type of the array array is: int32
New Array:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
