In [4]:
'''	
@Author: Aishwarya
@Date: 2021-12-7
@Title : concatenate two 2-dimensional arrays.
'''
########################################################################################################
import numpy as np
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2= np.array([[0, 2, 4], [6, 8, 10]])
print("Array1 : ")
print(arr1)
print("Array2 : ")
print(arr2)
arr3 = np.concatenate((arr1, arr2), 1)
print("Concatenated Array1 and Array2 :")
print(arr3)


Array1 : 
[[0 1 3]
 [5 7 9]]
Array2 : 
[[ 0  2  4]
 [ 6  8 10]]
Concatenated Array1 and Array2 :
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
