In [1]:
'''	
@Author: Aishwarya
@Date: 2021-12-7
@Title : a 3-D array with ones on a diagonal and zeros elsewhere.
'''
########################################################################################################
import numpy as np
array = np.eye(3)
print("Array :")
print(array)


Array :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
