In [13]:
'''	
@Author: Aishwarya
@Date: 2021-12-6
@Last Modified: 2021-12-1
@Title: convert list and tuple to array
'''
##################################################################################################################
import numpy as np

my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
