In [6]:
'''	
@Author: Aishwarya
@Date: 2021-12-6
@Title : Create a 3x3 matrix with values ranging from 2 to 10
'''
########################################################################################################
import numpy as np

list=[]
for i in range(2,11):
    list.append(i)
print("List :",list)
print()
arr=np.array(list)
arr2=arr.reshape(3,3)
print("Matrix 3x3 :")
print(arr2)

List : [2, 3, 4, 5, 6, 7, 8, 9, 10]

Matrix 3x3 :
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
