In [1]:
'''	
@Author: Aishwarya
@Date: 2021-12-7
@Title : an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
'''
########################################################################################################
import numpy as np
arr= np.arange(12).reshape(3, 4)
print("Array:")
print(arr)
for a in np.nditer(arr, op_flags=['readwrite']):
    a[...] = 3 * a
print("Array elements x 3:")
print(arr)


Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array elements x 3:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
