In [4]:
'''	
@Author: Aishwarya
@Date: 2021-12-7
@Title : save a NumPy array to a text file.
'''
########################################################################################################
import numpy as np


List = [1, 2, 3, 4, 5]
Array = np.array(List)


print('Array:\n', Array)
np.savetxt("textfile.txt", Array)

content = np.loadtxt('textfile.txt')
print("\nContent in file.txt:\n", content)


Array:
 [1 2 3 4 5]

Content in file.txt:
 [1. 2. 3. 4. 5.]


In [5]:

import numpy

# Creating an array
List = [1, 2, 3, 4, 5]
Array = numpy.array(List)

# Displaying the array
print('Array:\n', Array)
file = open("textfile1.txt", "w+")

# Saving the array in a text file
content = str(Array)
file.write(content)
file.close()

# Displaying the contents of the text file
file = open("textfile1.txt", "r")
content = file.read()

print("\nContent in textfile1.txt:\n", content)
file.close()


Array:
 [1 2 3 4 5]

Content in textfile1.txt:
 [1 2 3 4 5]
