In [1]:
'''	
@Author: Aishwarya
@Date: 2021-12-6
@Title: create a 2d array with 1 on the border and 0 inside
'''
########################################################################################################
import numpy as np

arr = np.ones((5,5))
print("Array:")
print(arr)
print("------------------------------------------------")
print("1 on the border and 0 inside array")
arr[1:-1,1:-1] = 0
print(arr)


Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------------------------------------
1 on the border and 0 inside array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
